import re
from playwright.sync_api import Page, expect
import time


def test_example(page: Page) -> None:
    time.sleep(2)
    page.goto("https://www2.acc.menzis.nl/zakelijk")
    time.sleep(8)
    page.get_by_role("button", name="Accepteren").click()
    page.get_by_label("Knop gebruikers menu").click()
    time.sleep(2)
    page.get_by_role("button", name="Menzis Zakelijk Onegini ACC").click()
    page.get_by_placeholder("naam@domein.com").click()
    page.get_by_placeholder("naam@domein.com").fill("ssz1@menzis.nl")
    page.get_by_placeholder("naam@domein.com").click(modifiers=["ControlOrMeta"])
    time.sleep(2)
    page.get_by_placeholder("Kies een wachtwoord").click()
    page.get_by_placeholder("Kies een wachtwoord").fill("Stop-01")
    time.sleep(2)
    page.get_by_role("button", name="Inloggen").click()
    time.sleep(15)
    page.get_by_role("link", name="Boek een interventie").click()
    time.sleep(2)
    page.get_by_role("link", name=" Mentaal").click()
    time.sleep(2)
    page.get_by_role("link", name="@Work Max12 Work Max12 is een").click()
    time.sleep(2)
    page.get_by_role("link", name="Direct bestellen").click()
    page.locator(".dummy").first.click()
    time.sleep(2)
    page.locator("fieldset:nth-child(6) > div > .formfield-group > .field-validation-valid > .input-group > div > .radio-label > .input-radio > .dummy").first.click()
    page.get_by_placeholder("Vul hier de naam van de medewerker in").click()
    page.get_by_placeholder("Vul hier de naam van de medewerker in").fill("Pieter")
    time.sleep(2)
    page.get_by_placeholder("Vul hier het e-mailadres van").click()
    page.get_by_placeholder("Vul hier het e-mailadres van").fill("SSZ1@menzis.nl")
    time.sleep(2)
    page.get_by_placeholder("Vul hier het telefoonnummer").click()
    page.get_by_placeholder("Vul hier het telefoonnummer").fill("0612345678")
    time.sleep(2)
    page.get_by_placeholder("Vul hier het adres van de").click()
    page.get_by_placeholder("Vul hier het adres van de").fill("Winschoterdiep 70")
    page.get_by_placeholder("Vul hier het adres van de").press("Tab")
    page.get_by_placeholder("Vul hier de postcode van de").click()
    page.get_by_placeholder("Vul hier de postcode van de").fill("9723 AB")
    page.get_by_placeholder("Vul hier de woonplaats van de").click()
    page.get_by_placeholder("Vul hier de woonplaats van de").fill("Groningen")
    time.sleep(2)
    page.get_by_placeholder("Eventuele toelichting").click()
    page.get_by_placeholder("Eventuele toelichting").fill("Lorum van de Ipsum")
    time.sleep(2)
    page.get_by_role("button", name="Verzenden").click()
    page.get_by_label("Knop gebruikers menu").click()
    time.sleep(2)
    page.get_by_role("link", name="Terug naar Portaal").click()
    page.get_by_role("link", name="Vitaliteitsbudget en").click()
    time.sleep(2)
    page.get_by_label("Boekjaar").select_option("2023")
    time.sleep(2)
    page.get_by_label("Boekjaar").select_option("2022")
    page.get_by_label("Boekjaar").select_option("2021")
    page.get_by_label("Knop gebruikers menu").click()
    time.sleep(2)
    page.get_by_role("link", name="Terug naar Portaal").click()
    page.get_by_role("link", name="Collectieve zorgverzekering").click()
    time.sleep(2)
    page.get_by_role("link", name="Documenten").click()
    time.sleep(2)
    page.get_by_role("link", name="Bedrijfsgegevens").click()
    time.sleep(2)
    page.get_by_role("link", name="Uw team").click()
    time.sleep(2)
    page.get_by_role("link", name="Contactpersonen").click()
    time.sleep(2)
    page.get_by_role("link", name="Wijzig contactpersonen").click()
    time.sleep(2)
    page.get_by_label("Knop gebruikers menu").click()
    time.sleep(2)
    page.get_by_label("gebruikersmenu", exact=True).get_by_role("link", name="Uitloggen").click()
